### ISSUE TITLE
Continuous integration?

### ISSUE THREAD

**Issue by relative-rene** [Smiranin/ng-deploy-gh-pages#2]
I took the steps and published the app on gh-pages. I can know longer npm start the app without the terminal saying i'm missing packages. 

is their an FAQ

**Comment by Smiranin** [comment]
What exactly does the terminal say?

**Comment by relative-rene** [comment]
Thanks for the quick response..
I ran
Renes-MBP:neptunes rarellano$ npm start
> neptunes@0.0.0 start /Users/rarellano/neptunes
> ng serve

ENOENT: no such file or directory, stat '/Users/rarellano/neptunes/src/tsconfig.app.json'
Error: ENOENT: no such file or directory, stat '/Users/rarellano/neptunes/src/tsconfig.app.json'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at AotPlugin._setupOptions (/Users/rarellano/neptunes/node_modules/@ngtools/webpack/src/plugin.js:58:16)
    at new AotPlugin (/Users/rarellano/neptunes/node_modules/@ngtools/webpack/src/plugin.js:26:14)
    at _createAotPlugin (/Users/rarellano/neptunes/node_modules/@angular/cli/models/webpack-configs/typescript.js:55:12)
    at Object.exports.getNonAotConfig (/Users/rarellano/neptunes/node_modules/@angular/cli/models/webpack-configs/typescript.js:70:19)
    at NgCliWebpackConfig.buildConfig (/Users/rarellano/neptunes/node_modules/@angular/cli/models/webpack-config.js:27:37)
    at Class.run (/Users/rarellano/neptunes/node_modules/@angular/cli/tasks/serve.js:39:98)
    at check_port_1.checkPort.then.port (/Users/rarellano/neptunes/node_modules/@angular/cli/commands/serve.js:110:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! neptunes@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the neptunes@0.0.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the neptunes package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs neptunes
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls neptunes
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rarellano/neptunes/npm-debug.log

The files exist.
I've reinstalled my angular-cli and npm.

**Comment by Smiranin** [comment]
I think you have a problem with angular cli. Check your angular-cli.json file. The ng-deploy package works with only ng serve command of angular-cli and several git commands.
